### PR TITLE
Bikes screen - stations swiper

### PR DESCRIPTION
**Pull request by indydedeken**
Stations swipe

### CODE REVIEW

**Comment by Phyks** [comment]
I do not have much internet access this week, I check this ASAP and merge it =) Sorry for the delay…

**Comment by indydedeken** [comment]
@Phyks no problem :wink:

**Comment by eliemichel** [comment]
@indydedeken I think you could loop the slider (slide to the right on the last station comes back to the first one).

**Comment by indydedeken** [comment]
@eliemichel just did it #15

**Pull request merged**
