### PR TITLE
Design

### PR DESCRIPTION
**Pull request by indydedeken**
The App header works and respect black box driven coding style

### CODE REVIEW

**Comment by Phyks** [comment]
@indydedeken I'm ok to merge it, could you rebase on the current master and include a fix for https://github.com/Phyks/VelibFxos/issues/6 for easy merging ?

Thanks!

**Comment by indydedeken** [comment]
@Phyks :+1:

**Comment by Phyks** [comment]
Really nice for the design. I get an undefined in `app.js` on line 334 however, and it does not fetch the stations. Sorry, I am not having much time to look at it right now, I might be able to spend some time on it within two weeks to finish the app with you guys :)

**Comment by Phyks** [comment]
My bad, I forgot this was not reimplemented yet in the design branch, there is a big `TODO` in the code ><

**Pull request merged**
