### PR TITLE
Initialisation Map.js

### PR DESCRIPTION
**Pull request by indydedeken**
Welcome to the new Black Box Class - **Map.js** - 

Created to initiate works with the maps : 
- available bikes/stands,
- search.

### CODE REVIEW

**Comment by Phyks** [comment]
On Firefox, I no longer have the station list displayed (but stations are correctly fetched according to the console). Apart from this, I'm ok to merge.

**Comment by indydedeken** [comment]
I commented <code>mySwiper</code> stuff because it was in trouble since @eliemichel split <code>app.js</code>. I think he forgot this little part of code : 

<pre>var mySwiper = new Swiper('.swiper-container', {       
// general settings
hashNav: false,
keyboardControl: true,
calculateHeight: true,
// pagination settings
loop: true,
pagination: '.pagination',
paginationClickable: true,
createPagination: true
});</pre>

But, it was not really implemented. Just for testing, that's why I don't care about this little bug.

@Phyks @eliemichel do you think we should create another JS file for swipper ?

**Comment by eliemichel** [comment]
Yep, that variable needs to be encapsulated into something.
It may be a new black box, or a variable inside Views, but it was definitely misdesigned.

(Actually I reported it at first, but losed it in the next PR merging)

**Comment by indydedeken** [comment]
@Phyks @eliemichel it's ok

**Comment by indydedeken** [comment]
Il y a un souci avec cette PR ?

**Comment by eliemichel** [comment]
Oops, @Phyks said me he would do it so I just skipped it…
Merging now.

**Pull request merged**
