### PR TITLE
Footer and station page implementation

### PR DESCRIPTION
**Pull request by edouardalvescamilo**
You will find in this pull request a implementation of the footer and the page giving all the details about a specific station (available bikes, stands, etc).

### CODE REVIEW

**Comment by eliemichel** [comment]
On my Flame, there seems to be a graphical glitch on the return arrow, as illustrated here:
flame8_bug_velib_arrow

But it may not be directly related to this PR…

edit: And I did not tried the right version…

**Comment by indydedeken** [comment]
@eliemichel Linked to the Mozilla header png #13

**Comment by eliemichel** [comment]
Yep, I've seen this, but I just notify from the glitch although I do not know where it comes from.

About footer, I think the "plus" image could be centered, and the margin would rather be the same horizontally and vertically.

**Comment by eliemichel** [comment]
@edouardalvescamilo 
Before accepting this PR, you should:
- Remove and .gitignore `*.css.bak` file(s)
- Rename image files using dashed-names instead of camlCase
- Rename and .gitignore `*.Thumbs`
- Remove `maquette.svg`. It is not used by the application itself and should go to the `doc` directory, which already contains it (named `mockup.svg`)

I know that it has not been respected until now, but please prefere using exclusively **english names** in all file names and code.

**Comment by eliemichel** [comment]
And the input field seems to be read-only. Is it expected?

**Comment by edouardalvescamilo** [comment]
Done ! :)

Input field behaviour is good for me.

**Comment by eliemichel** [comment]
`Thumbs.db` is still there. ;)

**Comment by edouardalvescamilo** [comment]
Deleted.

**Pull request merged**
